const { chromium } = require(process.env.CL_PLAYWRIGHT_MODULE || 'playwright');
const fs = require('fs');
const assert = require('node:assert/strict');
const base = process.env.CL_TEST_BASE_URL;
if (!base) throw new Error('CL_TEST_BASE_URL must point to a disposable SillyTavern instance; this test imports and edits synthetic cards.');
const out = process.env.CL_TEST_OUTPUT || require('path').join(require('os').tmpdir(), 'character-library-smoke');
fs.mkdirSync(out, { recursive: true });
const root = '/scripts/extensions/third-party/SillyTavern-CharacterLibrary';
const report = { checks: [], errors: [], networkErrors: [] };
const check = (name, detail) => { report.checks.push({name, detail}); console.log('PASS', name, detail || ''); };
let browser;
(async () => {
 browser = await chromium.launch({...(process.env.CL_BROWSER_PATH ? { executablePath: process.env.CL_BROWSER_PATH } : {}), headless:true});
 const context = await browser.newContext({viewport:{width:1440,height:1000}});
 const token = (await (await context.request.get(base+'/csrf-token')).json()).token;
 const headers = {'X-CSRF-Token':token};
 const post = async (url,data) => { const res=await context.request.post(base+url,{headers,data}); assert.ok(res.ok(),url+' '+res.status()+' '+await res.text()); return res.json(); };
 const run = Date.now();
 const cards = [];
 for (const [name,tags] of [['Alpha',['fantasy','constructor']],['Beta',['science']],['Gamma',['fantasy','magic']]]) {
  const card={spec:'chara_card_v2',spec_version:'2.0',data:{name:`CL QA ${run} ${name}`,description:'An original test description '+name,personality:'Curious',scenario:'Test world',first_mes:'Hello '+name,mes_example:'Example',creator:'QA Author',creator_notes:'QA notes',character_version:'1.0',tags,alternate_greetings:['Alt one','Alt two'],character_book:{name:'Test book',entries:[{id:1,keys:['test'],content:'Embedded lore',enabled:true,insertion_order:1}]},extensions:{qa:{preserve:'unchanged'}}}};
  const r=await context.request.post(base+'/api/characters/import',{headers,multipart:{file_type:'json',avatar:{name:name+'.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(card))}}});
  assert.ok(r.ok()); const imported=await r.json();assert.ok(imported.file_name,JSON.stringify(imported));cards.push({name:card.data.name,avatar:imported.file_name+'.png',card});
 }
 check('Real SillyTavern imports V2 JSON fixtures',cards.map(c=>c.avatar));
 const page = await context.newPage();
 page.on('pageerror',e=>report.errors.push(e.message));
 page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(base))report.networkErrors.push({status:r.status(),url:r.url()});});
 await page.route('**/*',r=>r.request().url().startsWith(base)||r.request().url().startsWith('data:')||r.request().url().startsWith('blob:')?r.continue():r.abort());
 await page.goto(base+root+'/app/library.html?csrf='+token);
 await page.waitForFunction(()=>window.ModuleLoader?.initialized && !document.documentElement.classList.contains('cl-initial-loading'));
 assert.equal(await page.evaluate(()=>ProviderRegistry.getAllProviders().length),9);
 check('Real app and nine provider registrations initialize');
 await page.locator('#searchInput').fill('CL QA '+run);
 await page.waitForFunction(()=>document.querySelectorAll('#characterGrid .char-card').length===3);
 check('Search finds the three imported cards');
 await page.locator('[data-select-id=sortSelect] .custom-select-trigger').click();
 await page.locator('.custom-select-menu:not(.hidden) [data-value="name_desc"]').click();
 await page.waitForFunction(()=>document.querySelector('#characterGrid .card-name')?.textContent.endsWith('Gamma'));
 await page.locator('[data-select-id=sortSelect] .custom-select-trigger').click();
 await page.locator('.custom-select-menu:not(.hidden) [data-value="name_asc"]').click();
 await page.waitForFunction(()=>document.querySelector('#characterGrid .card-name')?.textContent.endsWith('Alpha'));
 check('Ascending and descending name sort');
 await page.locator('#characterGrid .char-card').first().click();
 await page.waitForFunction(()=>!document.querySelector('#charModal').classList.contains('hidden'));
 assert.ok((await page.locator('#modalTitle').textContent()).includes('Alpha'));
 await page.locator('#charModal [data-tab="edit"]').click();
 assert.equal(await page.locator('#editDescription').evaluate(el=>el.readOnly),true);
 await page.locator('#toggleEditLockBtn').click();
 await page.locator('#editDescription').fill('Persisted edit through the real API');
 await page.locator('#editCreatorNotes').fill('Updated QA notes');
 await page.locator('#saveEditBtn').click();
 await page.locator('#confirmSaveBtn').click();
 await page.waitForFunction(()=>document.querySelector('#confirmSaveModal').classList.contains('hidden')&&document.querySelector('#editDescription').readOnly);
 const stored=await post('/api/characters/get',{avatar_url:cards[0].avatar});
 assert.equal(stored.data.description,'Persisted edit through the real API');
 assert.equal(stored.data.extensions.qa.preserve,'unchanged');
 assert.deepEqual(stored.data.alternate_greetings,['Alt one','Alt two']);
 assert.equal(stored.data.character_book.entries[0].content,'Embedded lore');
 check('Edit/save roundtrip preserves unknown extensions, greetings and lorebook');
 await page.locator('#favoriteCharBtn').click();
 await page.waitForTimeout(300);
 assert.equal((await post('/api/characters/get',{avatar_url:cards[0].avatar})).data.extensions.fav,true);
 check('Favorite persists in the real card');
 await page.locator('#modalClose').click();
 await page.waitForFunction(()=>document.querySelector('#charModal').classList.contains('hidden'));
 await page.screenshot({path:out+'/core-desktop.png',fullPage:true});
 const moduleNames = await page.evaluate(async()=>{for(const name of Object.keys(ModuleLoader._lazyLoaders))await ModuleLoader.ensureLoaded(name);await ensureExtractorsLoaded();return Object.keys(ModuleLoader.modules);});
 check('All lazy modules and gallery extractors load',moduleNames);
 await page.reload();
 await page.waitForFunction(()=>window.ModuleLoader?.initialized&&!document.documentElement.classList.contains('cl-initial-loading'));
 await page.locator('#searchInput').fill(cards[0].name);
 await page.waitForFunction(()=>document.querySelectorAll('#characterGrid .char-card').length===1);
 await page.locator('#characterGrid .char-card').click();
 await page.locator('#charModal [data-tab=edit]').click();
 await page.waitForFunction(()=>document.querySelector('#editDescription').value==='Persisted edit through the real API');
 check('Reload restores saved card');
 report.cards=cards.map(({card,...rest})=>rest);
 report.token=undefined;
 await page.screenshot({path:out+'/core-details.png',fullPage:true});
 assert.deepEqual(report.errors,[]);
})().catch(e=>{report.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(out+'/core-results.json',JSON.stringify(report,null,2));await browser?.close();});
